disabled_rules:
  - closure_spacing
  - colon
  - cyclomatic_complexity
  - empty_enum_arguments
  - fatal_error_message
  - file_length
  - force_cast
  - force_try
  - force_unwrapping
  - function_body_length
  - function_parameter_count
  - identifier_name
  - implicitly_unwrapped_optional
  - large_tuple
  - legacy_cggeometry_functions
  - legacy_constant
  - legacy_constructor
  - legacy_nsgeometry_functions
  - line_length
  - nesting
  - operator_usage_whitespace
  - redundant_string_enum_value
  - redundant_void_return
  - return_arrow_whitespace
  - shorthand_operator
  - syntactic_sugar
  - todo
  - type_body_length
  - type_name
  - unused_closure_parameter
  - unused_optional_binding
  - vertical_whitespace
  - void_return
  - custom_rules
  - trailing_whitespace
  - trailing_newline